Name:           ros-indigo-spur-description
Version:        0.2.6
Release:        0%{?dist}
Summary:        ROS spur_description package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/spur_description
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-gazebo-plugins
Requires:       ros-indigo-rviz
Requires:       ros-indigo-urdf
Requires:       ros-indigo-urdf-tutorial
Requires:       ros-indigo-xacro
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-urdf
BuildRequires:  ros-indigo-xacro

%description
A package for storing 3D model of SPUR omni-directional mobile manipulator robot
made at Tamagawa University.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Oct 05 2015 Hiroyuki Okada <okdhryk@gmail.com> - 0.2.6-0
- Autogenerated by Bloom

* Sat Jul 11 2015 Hiroyuki Okada <okdhryk@gmail.com> - 0.2.4-0
- Autogenerated by Bloom

* Thu Jul 02 2015 Hiroyuki Okada <okdhryk@gmail.com> - 0.2.3-0
- Autogenerated by Bloom

* Tue Jun 30 2015 Hiroyuki Okada <okdhryk@gmail.com> - 0.2.2-0
- Autogenerated by Bloom

* Wed May 13 2015 Hiroyuki Okada <okdhryk@gmail.com> - 0.2.1-0
- Autogenerated by Bloom

* Sat May 09 2015 Hiroyuki Okada <okdhryk@gmail.com> - 0.2.0-0
- Autogenerated by Bloom

* Thu May 07 2015 TORK <dev@opensource-robotics.tokyo.jp> - 0.1.3-0
- Autogenerated by Bloom

* Thu May 07 2015 TORK <dev@opensource-robotics.tokyo.jp> - 0.1.2-0
- Autogenerated by Bloom

* Wed Apr 29 2015 TORK <dev@opensource-robotics.tokyo.jp> - 0.1.1-0
- Autogenerated by Bloom

* Mon Mar 30 2015 TORK <dev@opensource-robotics.tokyo.jp> - 0.1.0-0
- Autogenerated by Bloom

