<?xml version="1.0"?>
<robot name="spur"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="ns" value="spur" />

  <!-- include materials -->
  <xacro:include filename="$(find spur_description)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find spur_description)/urdf/spur.gazebo.xacro" />

  <!-- constants -->
  <property name="M_PI" value="3.1415926535897931" />

  <property name="wheel_radius" value="0.05" />
  <property name="wheel_width" value="0.02" />

  <property name="base_width" value="0.30" />
  <property name="base_height" value="0.030" />
  <property name="caster_offset_x" value="0.15" />
  <property name="caster_offset_y" value="0.15" />
  <property name="caster_offset_z" value="0.14" />
  
  <!-- Hokuyo https://www.hokuyo-aut.jp/02sensor/07scanner/urg_04lx.html -->
  <property name="hokuyo_length" value="0.07" />
  <property name="hokuyo_radius" value="0.043" /> <!-- Because max surface area of Hokuyo laser is not cylindrical, this isn't accurate, which shouldn't matter. -->

  <property name="mx160_effort" value="8.3" /> <!--  8.3 N/m ?? 45rpm -> 4.71 rad/s-->
  <property name="mx160_velocity" value="4.71" />
  <!-- inertia -->
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
  </macro>

  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
              iyy="${m*(z*z+x*x)/12}" iyz = "0" izz="${m*(x*x+y*y)/12}" />
  </macro>
  <!-- wheel -->
  <xacro:macro name="odom_wheel_tire" params="parent suffix offset">

    <joint name="${parent}_wheel_tire_${suffix}" type="fixed">
      <origin xyz="0 0 ${offset}" rpy="0 0 0" />
      <parent link="${parent}_wheel_link" />
      <child link="${parent}_wheel_tire_${suffix}_link" />
    </joint>

    <link name="${parent}_wheel_tire_${suffix}_link">
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_width}" />
      </inertial>
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>

    <xacro:gazebo_tire_link name="${parent}_wheel_tire_${suffix}_link"  color="Black" />

  </xacro:macro>

  <xacro:macro name="odom_wheel_schaft" params="suffix rot_axis">

    <joint name="${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 0 ${rot_axis}" />
      <limit effort="${mx160_effort*500}" velocity="${mx160_velocity*100}"/>
      <dynamics damping="0.0" friction="0.0" />
      <origin xyz="0 0 -${caster_offset_z}" rpy="-${M_PI/2} 0 0" />
      <parent link="${suffix}_rotation_link" />
      <child link="${suffix}_wheel_link" />
    </joint>

    <xacro:simple_transmission name="${suffix}_wheel_joint" interface="EffortJointInterface" />

    <link name="${suffix}_wheel_link">
      <inertial>
        <mass value="5.0" />
        <origin xyz="0 0 0" />
        <cylinder_inertia m="5.0" r="0.02" h="0.100" />
      </inertial>
      <visual>
        <geometry>
          <cylinder length="0.100" radius="0.02"/>
        </geometry>
        <material name="Grey" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="${0.100 - wheel_width*2 - 0.01}" radius="0.02"/> <!-- avoid collision to tire -->
        </geometry>
      </collision>
    </link>

    <xacro:gazebo_tire_link name="${suffix}_wheel_link"  color="Grey" />

  </xacro:macro>

  <xacro:macro name="odom_wheel_rotate" params="suffix">
    <joint name="${suffix}_rotation_joint" type="revolute">
      <axis xyz="0 0 -1" />
      <limit lower="${-90*M_PI/180.0}" upper="${90*M_PI/180.0}" effort="${mx160_effort}" velocity="${mx160_velocity}"/>
      <dynamics damping="0.0" friction="0.0" />
      <xacro:insert_block name="origin" />
      <parent link="base_link"/>
      <child link="${suffix}_rotation_link" />
    </joint>

    <xacro:simple_transmission name="${suffix}_rotation_joint" interface="EffortJointInterface" />

    <link name="${suffix}_rotation_link">
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 -${caster_offset_z/2}" rpy="0 0 0" />
        <cylinder_inertia m="1.0" r="0.015" h="${caster_offset_z}" />
      </inertial>
      <visual>
        <origin xyz="0 0 -${caster_offset_z/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${caster_offset_z}" radius="0.015"/>
        </geometry>
        <material name="LightGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 -${caster_offset_z/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${caster_offset_z-0.05}" radius="0.015"/> <!-- avoid collision for wheel_schaft radius(0.02) -->
        </geometry>
      </collision>
    </link>

    <xacro:gazebo_base_link name="${suffix}_rotation_link"  color="White" />

  </xacro:macro>

  <xacro:macro name="odom_wheel" params="suffix *origin rot_axis">

    <xacro:odom_wheel_rotate suffix="${suffix}" />
    <xacro:odom_wheel_schaft suffix="${suffix}" rot_axis="${rot_axis}" />
    <xacro:odom_wheel_tire parent="${suffix}" suffix="l" offset="${0.05-wheel_width/2}"  />
    <xacro:odom_wheel_tire parent="${suffix}" suffix="r" offset="-${0.05-wheel_width/2}" />

  </xacro:macro>

  <!-- arm -->
  <xacro:macro name="mx_106_link" params="name *origin">

    <link name="${name}">
      <inertial>
        <xacro:insert_block name="origin" />
        <mass value="0.153" />
        <box_inertia m="0.153" x="0.029" y="0.0595" z="0.046" />
      </inertial>
      <visual>
        <xacro:insert_block name="origin" />
        <geometry>
          <box size="0.029 0.0595 0.046" />
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <xacro:insert_block name="origin" />
        <geometry>
          <box size="${0.029-0.01} ${0.0595-0.01} ${0.046-0.01}" />
        </geometry>
      </collision>
    </link>

    <xacro:gazebo_arm_link name="${name}"  color="Black" />

  </xacro:macro>

  <xacro:macro name="arm_link_element" params="name length offset" >
    <link name="${name}">
      <inertial>
        <origin xyz="-${length/2 - 0.0145} 0 ${offset}" />
        <mass value="0.1" />
        <box_inertia m="0.1" x="${length-0.1}" y="0.029" z="0.005" />
      </inertial>
      <visual>
        <origin xyz="-${length/2 - 0.0145} 0 ${offset}" />
        <geometry>
          <box size="${length} 0.029 0.005" />
        </geometry>
        <material name="LightGrey" />
      </visual>
      <collision>
        <origin xyz="-${length/2 - 0.0145} 0 ${offset}"/>
        <geometry>
          <box size="${length-0.1} 0.029 0.005" /> <!-- -0.06 to avoid self collision -->
        </geometry>
      </collision>

      <xacro:gazebo_arm_link name="${name}"  color="White" />

    </link>
  </xacro:macro>

  <xacro:macro name="arm_link_body" params="name length *origin" >
    <xacro:arm_link_element name="${name}_body_1" length="${length}" offset="0.023"/>
    <xacro:arm_link_element name="${name}_body_2" length="${length}" offset="-0.023"/>
    <joint name="${name}_body_fixed" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${name}_link" />
      <child link="${name}_body_1" />
    </joint>
    <joint name="${name}_body_2_fixed" type="fixed">
      <parent link="${name}_body_1" />
      <child link="${name}_body_2" />
    </joint>
  </xacro:macro>

  <xacro:macro name="arm_joint" params="parent name joint_origin_xyz joint_origin_rpy">

    <joint name="${name}_joint" type="revolute">
      <axis xyz="0 0 1" />
      <origin xyz="${joint_origin_xyz}" rpy="${joint_origin_rpy}" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
      <limit lower="${-90*M_PI/180.0}" upper="${90*M_PI/180.0}" effort="${mx160_effort}" velocity="${mx160_velocity}" />
    </joint>

    <xacro:simple_transmission name="${name}_joint" interface="EffortJointInterface" />

  </xacro:macro>

  <xacro:macro name="arm_link" params="parent name joint_origin_xyz joint_origin_rpy
                                       link_origin_xyz link_origin_rpy" >
    <xacro:arm_joint parent="${parent}" name="${name}"
                     joint_origin_xyz="${joint_origin_xyz}"
                     joint_origin_rpy="${joint_origin_rpy}" />
    <xacro:mx_106_link name="${name}_link" >
      <origin xyz="${link_origin_xyz}" rpy="${link_origin_rpy}" />
    </xacro:mx_106_link>

    <xacro:gazebo_base_link name="${name}_link"  color="Black" />

  </xacro:macro>

  <xacro:macro name="arm_links" params="prefix reflect" >

    <joint name="${prefix}_base_joint" type="fixed">
      <origin xyz="0 ${reflect * -0.15} 0.7" rpy="${M_PI/2} 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_base_link" />
    </joint>

    <xacro:mx_106_link name="${prefix}_base_link" >
      <origin xyz="0 0.01525 0" rpy="0 0 0" />
    </xacro:mx_106_link>

    <xacro:arm_link parent="${prefix}_base_link"
                    name="${prefix}_shoulder_p"
                    joint_origin_xyz="0 0 0" joint_origin_rpy="0 0 0"
                    link_origin_xyz="0 0 ${reflect * (0.1 - 0.01525)}"
                    link_origin_rpy="${M_PI/2} 0 ${M_PI/2}" />
    <xacro:arm_link parent="${prefix}_shoulder_p_link"
                    name="${prefix}_shoulder_r"
                    joint_origin_xyz="0 0 ${reflect * 0.1}"
                    joint_origin_rpy="0 ${M_PI/2} 0"
                    link_origin_xyz="0 -0.05 0"
                    link_origin_rpy="${M_PI/2} 0 0" />
    <xacro:arm_link parent="${prefix}_shoulder_r_link"
                    name="${prefix}_shoulder_y"
                    joint_origin_xyz="0 -0.1 0.0"
                    joint_origin_rpy="${M_PI/2} 0 0"
                    link_origin_xyz="0 0 ${0.2 - 0.01515}"
                    link_origin_rpy="${M_PI/2} 0 ${M_PI/2}" />
    <xacro:arm_link parent="${prefix}_shoulder_y_link"
                    name="${prefix}_elbow_p"
                    joint_origin_xyz="0 0 0.2" joint_origin_rpy="0 ${M_PI/2} 0"
                    link_origin_xyz="-${0.2 - 0.01525} 0 0"
                    link_origin_rpy="0 0 ${M_PI/2}" />
    <xacro:arm_link parent="${prefix}_elbow_p_link"
                    name="${prefix}_wrist_p"
                    joint_origin_xyz="-0.2 0 0" joint_origin_rpy="0 0
                                                                  0"
                    link_origin_xyz="-0.05 0 0"
                    link_origin_rpy="${M_PI/2} ${M_PI/2} 0" />
    <xacro:arm_joint parent="${prefix}_wrist_p_link"
                     name="${prefix}_wrist_r"
                     joint_origin_xyz="-0.05 0.03 0"
                     joint_origin_rpy="-${M_PI/2} -${M_PI/2} 0" />
    <link name="${prefix}_wrist_r_link" >
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.001" />
        <inertia  ixx="${(0.001/2*0.001/2+0.001/2*0.001/2)/3*0.001}"
                  ixy="0.0" ixz="0.0"
                  iyy="${(0.001/2*0.001/2+0.001/2*0.001/2)/3*0.001}"
                  iyz="0.0"
                  izz="${(0.001/2*0.001/2+0.001/2*0.001/2)/3*0.001}"
                  />
      </inertial>
      <visual>
        <geometry>
          <box size="0.02 0.02 0.02" />
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <geometry>
          <box size="0.12 0.01 0.01" />
        </geometry>
      </collision>
    </link>
    <xacro:gazebo_arm_link name="${prefix}_wrist_r_link" color="Black" />

    <xacro:arm_link_body name="${prefix}_elbow_p" length="0.2" >
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:arm_link_body>
    <xacro:arm_link_body name="${prefix}_shoulder_y" length="0.2" >
      <origin xyz="0 0 -0.02" rpy="0 ${M_PI/2} 0" />
    </xacro:arm_link_body>
    
  </xacro:macro>

  <!-- base -->
  <link name="base_link">
    <inertial>
      <mass value="10.0" />
      <origin xyz="0 0 0" />
      <box_inertia m="10.0" x="${base_width}" y="${base_width}" z="${base_height}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}" />
      </geometry>
      <material name="DarkGrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}" />
      </geometry>
    </collision>
  </link>

  <xacro:gazebo_base_link name="base_link"  color="Black" />
    
  <link name="base_footprint" />
  <joint name="footprint_to_base" type="fixed" >
    <origin xyz="0 0 0.190" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  odom base
  <xacro:odom_wheel suffix="fl" rot_axis="1">
    <origin xyz="${caster_offset_x} ${caster_offset_y} 0.0" rpy="0 0 0" />
  </xacro:odom_wheel>
  <xacro:odom_wheel suffix="fr" rot_axis="-1">
    <origin xyz="${caster_offset_x} -${caster_offset_y} 0.0" rpy="0 0 0" />
  </xacro:odom_wheel>
  <xacro:odom_wheel suffix="bl" rot_axis="1">
    <origin xyz="-${caster_offset_x} ${caster_offset_y} 0.0" rpy="0 0 0" />
  </xacro:odom_wheel>
  <xacro:odom_wheel suffix="br" rot_axis="-1">
    <origin xyz="-${caster_offset_x} -${caster_offset_y} 0.0" rpy="0 0 0" />
  </xacro:odom_wheel>

  <!-- URG -->
  <!-- http://answers.ros.org/question/44691/how-to-put-hokuyo-laser-sensor-on-p2os/?answer=44785#post-id-44785   -->
  <link name="hokuyo_sensor_link" type="laser">
    <inertial>
      <mass value="0.160" />
      <origin xyz="0 0 0.0" />
      <box_inertia m="0.160" x="0.05" y="0.05" z="0.05" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://gazebo_plugins/test/multi_robot_scenario/meshes/laser/hokuyo.dae"/>
      </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0.0" />
       <geometry>
         <box size="0.05 0.05 0.07" />
       </geometry>
     </collision>
  </link>
  <joint name="laser_to_base" type="fixed">
    <origin xyz="${caster_offset_x} 0 -0.05" rpy="3.14 0 0" />
    <parent link="base_link" />
    <child link="hokuyo_sensor_link"/>
  </joint>
    
  <!-- arm -->
  <xacro:arm_links prefix="rarm" reflect="1" />
  <xacro:arm_links prefix="larm" reflect="-1" />

  <!-- body -->
  <link name="body">
    <inertial>
      <mass value="10.0" />
      <origin xyz="0 0 0.25" />
      <box_inertia m="10.0" x="0.1" y="0.2" z="0.5" />
    </inertial>
    <visual>
      <origin xyz="0 0 0.25" />
      <geometry>
        <box size="0.1 0.2 0.5" />
      </geometry>
      <material name="LightGrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0.25" />
      <geometry>
        <box size="0.1 0.2 0.5" />
      </geometry>
    </collision>
  </link>

  <xacro:gazebo_base_link name="body"  color="White" />

  <joint name="base_to_body" type="fixed" >
    <origin xyz="0 0 0.30" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="body" />
  </joint>

</robot>
